# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:/Dropbox/Hobby/PRG/PyWork/FGet/view/ui/playlist_ui.ui'
#
# Created: Wed Mar 25 17:24:44 2015
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Playlist(object):
    def setupUi(self, Playlist):
        Playlist.setObjectName("Playlist")
        Playlist.resize(371, 577)
        self.centralwidget = QtWidgets.QWidget(Playlist)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_frame = QtWidgets.QFrame(self.centralwidget)
        self.top_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame.setObjectName("top_frame")
        self.top_layout = QtWidgets.QHBoxLayout(self.top_frame)
        self.top_layout.setSpacing(0)
        self.top_layout.setContentsMargins(0, 0, 0, 0)
        self.top_layout.setObjectName("top_layout")
        self.bn_open = QtWidgets.QToolButton(self.top_frame)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../qt_ui/files/icons/basic-application/open127.png"), QtGui.QIcon.Normal,
                       QtGui.QIcon.Off)
        self.bn_open.setIcon(icon)
        self.bn_open.setIconSize(QtCore.QSize(32, 32))
        self.bn_open.setAutoRaise(True)
        self.bn_open.setObjectName("bn_open")
        self.top_layout.addWidget(self.bn_open)
        self.bn_save = QtWidgets.QToolButton(self.top_frame)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../qt_ui/files/icons/basic-application/floppy13.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.bn_save.setIcon(icon1)
        self.bn_save.setIconSize(QtCore.QSize(32, 32))
        self.bn_save.setAutoRaise(True)
        self.bn_save.setObjectName("bn_save")
        self.top_layout.addWidget(self.bn_save)
        self.bn_add_from_fav = QtWidgets.QToolButton(self.top_frame)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../qt_ui/files/icons/basic-application/star82.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.bn_add_from_fav.setIcon(icon2)
        self.bn_add_from_fav.setIconSize(QtCore.QSize(32, 32))
        self.bn_add_from_fav.setAutoRaise(True)
        self.bn_add_from_fav.setObjectName("bn_add_from_fav")
        self.top_layout.addWidget(self.bn_add_from_fav)
        self.bn_delete = QtWidgets.QToolButton(self.top_frame)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../qt_ui/files/icons/basic-application/delete30.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.bn_delete.setIcon(icon3)
        self.bn_delete.setIconSize(QtCore.QSize(32, 32))
        self.bn_delete.setAutoRaise(True)
        self.bn_delete.setObjectName("bn_delete")
        self.top_layout.addWidget(self.bn_delete)
        self.verticalLayout.addWidget(self.top_frame)
        self.mid_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mid_frame.sizePolicy().hasHeightForWidth())
        self.mid_frame.setSizePolicy(sizePolicy)
        self.mid_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mid_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mid_frame.setObjectName("mid_frame")
        self.mid_layout = QtWidgets.QVBoxLayout(self.mid_frame)
        self.mid_layout.setSpacing(0)
        self.mid_layout.setContentsMargins(0, 0, 0, 0)
        self.mid_layout.setObjectName("mid_layout")
        self.playlist = QtWidgets.QListWidget(self.mid_frame)
        self.playlist.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.playlist.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.playlist.setSelectionRectVisible(True)
        self.playlist.setObjectName("playlist")
        self.mid_layout.addWidget(self.playlist)
        self.verticalLayout.addWidget(self.mid_frame)
        self.bottom_frame = QtWidgets.QFrame(self.centralwidget)
        self.bottom_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_frame.setObjectName("bottom_frame")
        self.bottom_layout = QtWidgets.QHBoxLayout(self.bottom_frame)
        self.bottom_layout.setSpacing(0)
        self.bottom_layout.setContentsMargins(0, 0, 0, 0)
        self.bottom_layout.setObjectName("bottom_layout")
        self.bn_prev = QtWidgets.QToolButton(self.bottom_frame)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../qt_ui/files/icons/basic-application/navigate5.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.bn_prev.setIcon(icon4)
        self.bn_prev.setIconSize(QtCore.QSize(32, 32))
        self.bn_prev.setAutoRaise(True)
        self.bn_prev.setObjectName("bn_prev")
        self.bottom_layout.addWidget(self.bn_prev)
        self.bn_play = QtWidgets.QToolButton(self.bottom_frame)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../qt_ui/files/icons/basic-application/arrow487.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.bn_play.setIcon(icon5)
        self.bn_play.setIconSize(QtCore.QSize(32, 32))
        self.bn_play.setAutoRaise(True)
        self.bn_play.setObjectName("bn_play")
        self.bottom_layout.addWidget(self.bn_play)
        self.bn_next = QtWidgets.QToolButton(self.bottom_frame)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../qt_ui/files/icons/basic-application/navigate4.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.bn_next.setIcon(icon6)
        self.bn_next.setIconSize(QtCore.QSize(32, 32))
        self.bn_next.setAutoRaise(True)
        self.bn_next.setObjectName("bn_next")
        self.bottom_layout.addWidget(self.bn_next)
        self.verticalLayout.addWidget(self.bottom_frame)
        Playlist.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Playlist)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 371, 21))
        self.menubar.setObjectName("menubar")
        Playlist.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Playlist)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        Playlist.setStatusBar(self.statusbar)

        self.retranslateUi(Playlist)
        QtCore.QMetaObject.connectSlotsByName(Playlist)

    def retranslateUi(self, Playlist):
        _translate = QtCore.QCoreApplication.translate
        Playlist.setWindowTitle(_translate("Playlist", "Playlist"))
        self.bn_open.setText(_translate("Playlist", "Load"))
        self.bn_save.setText(_translate("Playlist", "Save"))
        self.bn_add_from_fav.setText(_translate("Playlist", "Add from fav"))
        self.bn_delete.setText(_translate("Playlist", "Delete"))
        self.bn_prev.setText(_translate("Playlist", "Prev"))
        self.bn_play.setText(_translate("Playlist", "Play"))
        self.bn_next.setText(_translate("Playlist", "Next"))
