# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:/Repository/PyWork/fget/view/ui/setting_ui.ui'
#
# Created: Sun Feb 26 17:21:16 2017
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ConfigDialog(object):
    def setupUi(self, ConfigDialog):
        ConfigDialog.setObjectName("ConfigDialog")
        ConfigDialog.resize(463, 382)
        self.verticalLayout = QtWidgets.QVBoxLayout(ConfigDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(ConfigDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setSpacing(12)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabs = QtWidgets.QTabWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabs.sizePolicy().hasHeightForWidth())
        self.tabs.setSizePolicy(sizePolicy)
        self.tabs.setObjectName("tabs")
        self.tab_folders = QtWidgets.QWidget()
        self.tab_folders.setObjectName("tab_folders")
        self.formLayout = QtWidgets.QFormLayout(self.tab_folders)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.tab_folders)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.frame_5 = QtWidgets.QFrame(self.tab_folders)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.input_base_folder = QtWidgets.QLineEdit(self.frame_5)
        self.input_base_folder.setObjectName("input_base_folder")
        self.horizontalLayout_3.addWidget(self.input_base_folder)
        self.bn_base_folder = QtWidgets.QToolButton(self.frame_5)
        self.bn_base_folder.setObjectName("bn_base_folder")
        self.horizontalLayout_3.addWidget(self.bn_base_folder)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.frame_5)
        self.label = QtWidgets.QLabel(self.tab_folders)
        self.label.setObjectName("label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label)
        self.frame_3 = QtWidgets.QFrame(self.tab_folders)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.input_fav_file = QtWidgets.QLineEdit(self.frame_3)
        self.input_fav_file.setObjectName("input_fav_file")
        self.horizontalLayout.addWidget(self.input_fav_file)
        self.bn_fav_file = QtWidgets.QToolButton(self.frame_3)
        self.bn_fav_file.setObjectName("bn_fav_file")
        self.horizontalLayout.addWidget(self.bn_fav_file)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.frame_3)
        self.label_2 = QtWidgets.QLabel(self.tab_folders)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.frame_4 = QtWidgets.QFrame(self.tab_folders)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.input_playlist_file = QtWidgets.QLineEdit(self.frame_4)
        self.input_playlist_file.setObjectName("input_playlist_file")
        self.horizontalLayout_2.addWidget(self.input_playlist_file)
        self.bn_playlist_file = QtWidgets.QToolButton(self.frame_4)
        self.bn_playlist_file.setObjectName("bn_playlist_file")
        self.horizontalLayout_2.addWidget(self.bn_playlist_file)
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.frame_4)
        self.label_4 = QtWidgets.QLabel(self.tab_folders)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.frame_6 = QtWidgets.QFrame(self.tab_folders)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.input_dest_folder = QtWidgets.QLineEdit(self.frame_6)
        self.input_dest_folder.setObjectName("input_dest_folder")
        self.horizontalLayout_4.addWidget(self.input_dest_folder)
        self.bn_dest_folder = QtWidgets.QToolButton(self.frame_6)
        self.bn_dest_folder.setObjectName("bn_dest_folder")
        self.horizontalLayout_4.addWidget(self.bn_dest_folder)
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.frame_6)
        self.label_5 = QtWidgets.QLabel(self.tab_folders)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.frame_7 = QtWidgets.QFrame(self.tab_folders)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_5.setSpacing(4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.input_uget_folder = QtWidgets.QLineEdit(self.frame_7)
        self.input_uget_folder.setObjectName("input_uget_folder")
        self.horizontalLayout_5.addWidget(self.input_uget_folder)
        self.bn_uget_folder = QtWidgets.QToolButton(self.frame_7)
        self.bn_uget_folder.setObjectName("bn_uget_folder")
        self.horizontalLayout_5.addWidget(self.bn_uget_folder)
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.frame_7)
        self.label_6 = QtWidgets.QLabel(self.tab_folders)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.frame_10 = QtWidgets.QFrame(self.tab_folders)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_6.setSpacing(4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.input_exchange_folder = QtWidgets.QLineEdit(self.frame_10)
        self.input_exchange_folder.setObjectName("input_exchange_folder")
        self.horizontalLayout_6.addWidget(self.input_exchange_folder)
        self.bn_exchange_folder = QtWidgets.QToolButton(self.frame_10)
        self.bn_exchange_folder.setObjectName("bn_exchange_folder")
        self.horizontalLayout_6.addWidget(self.bn_exchange_folder)
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.frame_10)
        self.tabs.addTab(self.tab_folders, "")
        self.tab_actions = QtWidgets.QWidget()
        self.tab_actions.setObjectName("tab_actions")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_actions)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_8 = QtWidgets.QFrame(self.tab_actions)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.radio_use_uget = QtWidgets.QRadioButton(self.groupBox_3)
        self.radio_use_uget.setChecked(True)
        self.radio_use_uget.setObjectName("radio_use_uget")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.radio_use_uget)
        self.radio_use_dropbox = QtWidgets.QRadioButton(self.groupBox_3)
        self.radio_use_dropbox.setObjectName("radio_use_dropbox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.radio_use_dropbox)
        self.gridLayout_3.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_8)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.chk_download_simultaneously = QtWidgets.QCheckBox(self.groupBox_4)
        self.chk_download_simultaneously.setObjectName("chk_download_simultaneously")
        self.verticalLayout_6.addWidget(self.chk_download_simultaneously)
        self.gridLayout_3.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.frame_8, QtCore.Qt.AlignTop)
        self.frame_9 = QtWidgets.QFrame(self.tab_actions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.bn_download_now = QtWidgets.QPushButton(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bn_download_now.sizePolicy().hasHeightForWidth())
        self.bn_download_now.setSizePolicy(sizePolicy)
        self.bn_download_now.setObjectName("bn_download_now")
        self.verticalLayout_7.addWidget(self.bn_download_now, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.verticalLayout_5.addWidget(self.frame_9, QtCore.Qt.AlignBottom)
        self.tabs.addTab(self.tab_actions, "")
        self.tab_debug = QtWidgets.QWidget()
        self.tab_debug.setObjectName("tab_debug")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_debug)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.tab_debug)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.chk_controller_debug = QtWidgets.QCheckBox(self.groupBox)
        self.chk_controller_debug.setObjectName("chk_controller_debug")
        self.verticalLayout_3.addWidget(self.chk_controller_debug)
        self.chk_view_debug = QtWidgets.QCheckBox(self.groupBox)
        self.chk_view_debug.setObjectName("chk_view_debug")
        self.verticalLayout_3.addWidget(self.chk_view_debug)
        self.chk_model_debug = QtWidgets.QCheckBox(self.groupBox)
        self.chk_model_debug.setObjectName("chk_model_debug")
        self.verticalLayout_3.addWidget(self.chk_model_debug)
        self.chk_site_debug = QtWidgets.QCheckBox(self.groupBox)
        self.chk_site_debug.setObjectName("chk_site_debug")
        self.verticalLayout_3.addWidget(self.chk_site_debug)
        self.chk_fav_debug = QtWidgets.QCheckBox(self.groupBox)
        self.chk_fav_debug.setObjectName("chk_fav_debug")
        self.verticalLayout_3.addWidget(self.chk_fav_debug)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_debug)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.chk_statistic = QtWidgets.QCheckBox(self.groupBox_2)
        self.chk_statistic.setObjectName("chk_statistic")
        self.verticalLayout_4.addWidget(self.chk_statistic)
        self.chk_video_info = QtWidgets.QCheckBox(self.groupBox_2)
        self.chk_video_info.setObjectName("chk_video_info")
        self.verticalLayout_4.addWidget(self.chk_video_info)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.tab_debug)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.bn_recompile = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bn_recompile.sizePolicy().hasHeightForWidth())
        self.bn_recompile.setSizePolicy(sizePolicy)
        self.bn_recompile.setObjectName("bn_recompile")
        self.gridLayout_2.addWidget(self.bn_recompile, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.gridLayout.addWidget(self.frame_2, 2, 0, 1, 1, QtCore.Qt.AlignRight)
        self.tabs.addTab(self.tab_debug, "")
        self.verticalLayout_2.addWidget(self.tabs)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.frame)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(ConfigDialog)
        self.tabs.setCurrentIndex(1)
        self.buttonBox.accepted.connect(ConfigDialog.accept)
        self.buttonBox.rejected.connect(ConfigDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ConfigDialog)
        ConfigDialog.setTabOrder(self.chk_controller_debug, self.chk_view_debug)
        ConfigDialog.setTabOrder(self.chk_view_debug, self.chk_model_debug)
        ConfigDialog.setTabOrder(self.chk_model_debug, self.chk_site_debug)
        ConfigDialog.setTabOrder(self.chk_site_debug, self.chk_fav_debug)
        ConfigDialog.setTabOrder(self.chk_fav_debug, self.chk_statistic)
        ConfigDialog.setTabOrder(self.chk_statistic, self.chk_video_info)
        ConfigDialog.setTabOrder(self.chk_video_info, self.bn_recompile)
        ConfigDialog.setTabOrder(self.bn_recompile, self.input_base_folder)
        ConfigDialog.setTabOrder(self.input_base_folder, self.bn_base_folder)
        ConfigDialog.setTabOrder(self.bn_base_folder, self.input_fav_file)
        ConfigDialog.setTabOrder(self.input_fav_file, self.bn_fav_file)
        ConfigDialog.setTabOrder(self.bn_fav_file, self.input_playlist_file)
        ConfigDialog.setTabOrder(self.input_playlist_file, self.bn_playlist_file)
        ConfigDialog.setTabOrder(self.bn_playlist_file, self.input_dest_folder)
        ConfigDialog.setTabOrder(self.input_dest_folder, self.bn_dest_folder)
        ConfigDialog.setTabOrder(self.bn_dest_folder, self.input_uget_folder)
        ConfigDialog.setTabOrder(self.input_uget_folder, self.bn_uget_folder)

    def retranslateUi(self, ConfigDialog):
        _translate = QtCore.QCoreApplication.translate
        ConfigDialog.setWindowTitle(_translate("ConfigDialog", "Dialog"))
        self.label_3.setText(_translate("ConfigDialog", "Base folder"))
        self.bn_base_folder.setText(_translate("ConfigDialog", "..."))
        self.label.setText(_translate("ConfigDialog", "Favorites file"))
        self.bn_fav_file.setText(_translate("ConfigDialog", "..."))
        self.label_2.setText(_translate("ConfigDialog", "Playlist file"))
        self.bn_playlist_file.setText(_translate("ConfigDialog", "..."))
        self.label_4.setText(_translate("ConfigDialog", "Download folder"))
        self.bn_dest_folder.setText(_translate("ConfigDialog", "..."))
        self.label_5.setText(_translate("ConfigDialog", "uGet folder"))
        self.bn_uget_folder.setText(_translate("ConfigDialog", "..."))
        self.label_6.setText(_translate("ConfigDialog", "Data exchange folder"))
        self.bn_exchange_folder.setText(_translate("ConfigDialog", "..."))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_folders), _translate("ConfigDialog", "Folders"))
        self.groupBox_3.setTitle(_translate("ConfigDialog", "Download method"))
        self.radio_use_uget.setText(_translate("ConfigDialog", "Local UGET program"))
        self.radio_use_dropbox.setText(_translate("ConfigDialog", "Remote server via Dropbox"))
        self.groupBox_4.setTitle(_translate("ConfigDialog", "Download options"))
        self.chk_download_simultaneously.setText(_translate("ConfigDialog", "Remote download simultaneously (after close FGet)"))
        self.bn_download_now.setText(_translate("ConfigDialog", "Download now"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_actions), _translate("ConfigDialog", "Download"))
        self.groupBox.setTitle(_translate("ConfigDialog", "Degug flags"))
        self.chk_controller_debug.setText(_translate("ConfigDialog", "Controller"))
        self.chk_view_debug.setText(_translate("ConfigDialog", "View"))
        self.chk_model_debug.setText(_translate("ConfigDialog", "Model"))
        self.chk_site_debug.setText(_translate("ConfigDialog", "Site"))
        self.chk_fav_debug.setText(_translate("ConfigDialog", "Favorites"))
        self.groupBox_2.setTitle(_translate("ConfigDialog", "Info view"))
        self.chk_statistic.setText(_translate("ConfigDialog", "Show thumbnail statistic"))
        self.chk_video_info.setText(_translate("ConfigDialog", "Show video information"))
        self.bn_recompile.setText(_translate("ConfigDialog", "Recompile interfaces"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_debug), _translate("ConfigDialog", "Debug"))

