# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:/Repository/PyWork/fget/view/ui/tool_box_ui.ui'
#
# Created: Sun Feb 26 17:21:14 2017
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ToolBox(object):
    def setupUi(self, ToolBox):
        ToolBox.setObjectName("ToolBox")
        ToolBox.resize(398, 51)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ToolBox.sizePolicy().hasHeightForWidth())
        ToolBox.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(ToolBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setContentsMargins(4, 4, 4, 4)
        self.gridLayout.setObjectName("gridLayout")
        self.combo_category = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_category.sizePolicy().hasHeightForWidth())
        self.combo_category.setSizePolicy(sizePolicy)
        self.combo_category.setEditable(True)
        self.combo_category.setObjectName("combo_category")
        self.gridLayout.addWidget(self.combo_category, 0, 0, 1, 1)
        self.bn_edit = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bn_edit.sizePolicy().hasHeightForWidth())
        self.bn_edit.setSizePolicy(sizePolicy)
        self.bn_edit.setObjectName("bn_edit")
        self.gridLayout.addWidget(self.bn_edit, 1, 2, 1, 1)
        self.bn_add_page = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bn_add_page.sizePolicy().hasHeightForWidth())
        self.bn_add_page.setSizePolicy(sizePolicy)
        self.bn_add_page.setObjectName("bn_add_page")
        self.gridLayout.addWidget(self.bn_add_page, 1, 1, 1, 1)
        self.bn_filter = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bn_filter.sizePolicy().hasHeightForWidth())
        self.bn_filter.setSizePolicy(sizePolicy)
        self.bn_filter.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.bn_filter.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.bn_filter.setObjectName("bn_filter")
        self.gridLayout.addWidget(self.bn_filter, 1, 3, 1, 1)
        self.bn_go = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bn_go.sizePolicy().hasHeightForWidth())
        self.bn_go.setSizePolicy(sizePolicy)
        self.bn_go.setObjectName("bn_go")
        self.gridLayout.addWidget(self.bn_go, 0, 5, 2, 1)
        self.bn_add_thumb = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bn_add_thumb.sizePolicy().hasHeightForWidth())
        self.bn_add_thumb.setSizePolicy(sizePolicy)
        self.bn_add_thumb.setObjectName("bn_add_thumb")
        self.gridLayout.addWidget(self.bn_add_thumb, 1, 0, 1, 1)
        self.bn_config = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bn_config.sizePolicy().hasHeightForWidth())
        self.bn_config.setSizePolicy(sizePolicy)
        self.bn_config.setObjectName("bn_config")
        self.gridLayout.addWidget(self.bn_config, 1, 4, 1, 1)
        self.combo_url = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_url.sizePolicy().hasHeightForWidth())
        self.combo_url.setSizePolicy(sizePolicy)
        self.combo_url.setEditable(False)
        self.combo_url.setMaxVisibleItems(50)
        self.combo_url.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.combo_url.setObjectName("combo_url")
        self.gridLayout.addWidget(self.combo_url, 0, 1, 1, 4)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setColumnStretch(3, 1)
        ToolBox.setCentralWidget(self.centralwidget)

        self.retranslateUi(ToolBox)
        QtCore.QMetaObject.connectSlotsByName(ToolBox)

    def retranslateUi(self, ToolBox):
        _translate = QtCore.QCoreApplication.translate
        ToolBox.setWindowTitle(_translate("ToolBox", "Favorites"))
        self.bn_edit.setText(_translate("ToolBox", "Edit"))
        self.bn_add_page.setText(_translate("ToolBox", "Add page"))
        self.bn_filter.setText(_translate("ToolBox", "Filter"))
        self.bn_go.setText(_translate("ToolBox", "GO"))
        self.bn_add_thumb.setText(_translate("ToolBox", "Add thumbs"))
        self.bn_config.setText(_translate("ToolBox", "Config"))

